# Generated by Django 3.2.3 on 2021-06-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('alpha2_code', models.CharField(max_length=2)),
                ('alpha3_code', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sub_region', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area', models.FloatField(blank=True, default=0.0, null=True)),
                ('native_name', models.CharField(max_length=100)),
                ('flag', models.URLField()),
                ('numeric_code', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'api.country',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api.vaccine',
            },
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_field', models.DateField()),
                ('total_vaccinations', models.BigIntegerField()),
                ('people_vaccinated', models.BigIntegerField()),
                ('people_fully_vaccinated', models.BigIntegerField()),
                ('source_url', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('vaccine', models.ManyToManyField(to='api.Vaccine')),
            ],
            options={
                'db_table': 'api.vaccine_application',
            },
        ),
        migrations.CreateModel(
            name='TranslationsCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('de', models.CharField(blank=True, max_length=100, null=True)),
                ('es', models.CharField(blank=True, max_length=100, null=True)),
                ('fr', models.CharField(blank=True, max_length=100, null=True)),
                ('ja', models.CharField(blank=True, max_length=100, null=True)),
                ('it', models.CharField(blank=True, max_length=100, null=True)),
                ('br', models.CharField(blank=True, max_length=100, null=True)),
                ('pt', models.CharField(blank=True, max_length=100, null=True)),
                ('nl', models.CharField(blank=True, max_length=100, null=True)),
                ('hr', models.CharField(blank=True, max_length=100, null=True)),
                ('fa', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'verbose_name_plural': 'translation countries',
                'db_table': 'api.translation_country',
            },
        ),
        migrations.CreateModel(
            name='RecoveredPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'db_table': 'api.recovered_people',
            },
        ),
        migrations.CreateModel(
            name='DailyDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'db_table': 'api.daily_death',
            },
        ),
        migrations.CreateModel(
            name='DailyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'db_table': 'api.daily_case',
            },
        ),
        migrations.CreateModel(
            name='AlternativeNameCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('alternative_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'verbose_name_plural': 'alternative name countries',
                'db_table': 'api.alternative_name_country',
            },
        ),
        migrations.CreateModel(
            name='ActiveCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'db_table': 'api.active_case',
            },
        ),
    ]
