# Generated by Django 2.1.15 on 2021-05-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'api.active_case',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api.continent',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sub_region', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('native_name', models.CharField(max_length=100)),
                ('flag', models.URLField()),
                ('numeric_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Continent')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'api.country',
            },
        ),
        migrations.CreateModel(
            name='DailyCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'db_table': 'api.daily_case',
            },
        ),
        migrations.CreateModel(
            name='DailyDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'db_table': 'api.daily_death',
            },
        ),
        migrations.CreateModel(
            name='RecoveredPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'db_table': 'api.recovered_people',
            },
        ),
        migrations.CreateModel(
            name='TranslationsCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('de', models.CharField(max_length=100)),
                ('es', models.CharField(max_length=100)),
                ('fr', models.CharField(max_length=100)),
                ('ja', models.CharField(max_length=100)),
                ('it', models.CharField(max_length=100)),
                ('br', models.CharField(max_length=100)),
                ('pt', models.CharField(max_length=100)),
                ('nl', models.CharField(max_length=100)),
                ('hr', models.CharField(max_length=100)),
                ('fa', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'verbose_name_plural': 'translation countries',
                'db_table': 'api.translation_country',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api.vaccine',
            },
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField()),
                ('vaccinated_people', models.IntegerField()),
                ('full_vaccinated_people', models.IntegerField()),
                ('source_url', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('vaccine', models.ManyToManyField(to='api.Vaccine')),
            ],
            options={
                'db_table': 'api.vaccine_application',
            },
        ),
        migrations.AddField(
            model_name='activecase',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
    ]
