# Generated by Django 3.2.3 on 2021-06-22 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210622_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativenamecountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='api.country'),
        ),
        migrations.AlterField(
            model_name='alternativenamevaccine',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='api.vaccine'),
        ),
    ]
