from .daily_active_case_admin import DailyActiveCaseAdmin
from .country_admin import CountryAdmin
from .daily_confirmed_case_admin import DailyConfirmedCaseAdmin
from .daily_death_admin import DailyDeathAdmin
from .daily_recovered_people_admin import DailyRecoveredPeopleAdmin
from .translation_country_admin import TranslationsCountryAdmin
from .vaccine_admin import VaccineAdmin
from .vaccine_application_admin import VaccineApplicationAdmin
