from .active_case_admin import ActiveCaseAdmin
from .country_admin import CountryAdmin
from .daily_case_admin import DailyCaseAdmin
from .daily_death_admin import DailyDeathAdmin
from .recovered_people_admin import RecoveredPeopleAdmin
from .translation_country_admin import TranslationsCountryAdmin
from .vaccine_admin import VaccineAdmin
from .vaccine_application_admin import VaccineApplicationAdmin
