from .entity import Entity
from .country import Country
from .translation_country import TranslationsCountry
from .daily_active_case import DailyActiveCase
from .daily_confirmed_case import DailyConfirmedCase
from .daily_death import DailyDeath
from .daily_recovered_people import DailyRecoveredPeople
from .vaccine import Vaccine
from .vaccine_application import VaccineApplication
from .alternative_name_country import AlternativeNameCountry
from .alternative_name_vaccine import AlternativeNameVaccine
